export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_ITEM_CART = "INCREMENT_ITEM_CART";
export const DECREMENT_ITEM_CART = "DECREMENT_ITEM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";